backend:
  name: git-gateway

media_folder: source/images/uploads
public_folder: /images/uploads

# publish_mode: editorial_workflow #optional, enables publishing workflow

collections:
  - name: pages
    label: Pages
    files:
      - file: "data/pages/home.yml"
        label: Homepage
        name: home
        fields:
          - label: Header
            name: header
            widget: object
            fields:
              - {label: "Catchphrase", name: catchphrase, widget: string}

          - label: Activity
            name: activity
            widget: object
            fields:
              - {label: "Catchphrase", name: catchphrase, widget: string}
              - {label: "Institutions", name: institutions, widget: string}

          - label: Description
            name: description
            widget: object
            fields:
              - {label: "Catchphrase", name: catchphrase, widget: string}
              - {label: "Description", name: description_text, widget: string}

          - label: Buttons
            name: buttons
            widget: object
            fields:
              - {label: "Make an appointment", name: make_an_appointment, widget: string}
              - {label: "Become happy", name: become_happy, widget: string}
              - {label: "Join the team", name: join_the_team, widget: string}

  - name: settings
    label: Settings
    files:
      - file: data/settings/navigation.yml
        label: Navigation
        name: navigation
        fields:
          - label: Navigation
            name: nav_items
            widget: list
            fields:
              - {label: Label, name: label, widget: string}
              - {label: Path, name: path, widget: string}

      - file: data/settings/seo.yml
        label: SEO
        name: seo
        fields:
          - label: "Title"
            name: title
            widget: string
          - label: "Description"
            name: description
            widget: string
          - label: "og:image"
            name: "og_image"
            widget: image
          - label: "og:type"
            name: og_type
            widget: select
            options: ["website", "article", "blog", "company"]
            default: "website"

      - file: data/settings/contact.yml
        label: Contact
        name: contact
        fields:
          - label: Address Line 1
            name: address_line1
            widget: string
          - label: Address Line 2
            name: address_line2
            widget: string
          - label: Email
            name: email
            widget: string
          - label: Phone number
            name: phone_number
            widget: string

#      - file: data/settings/contact.yml
#        label: Contacts
#        name: contact_info
#        fields:
#          - label: Contact
#            name: contacts
#            widget: list
#            fields:
#              - {label: "Address Line 1", name: address_line1, widget: string}
#              - {label: "Address Line 2", name: address_line2, widget: string}
#              - {label: "Email", name: email, widget: string}
#              - {label: "Phone number", name: phone_number, widget: string}
